apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: zoro-objectstore
spec:
  configuration:
    destinationPath: "https://cloudlabbackupsstaging.blob.core.windows.net/zoro"
    azureCredentials:
      storageAccount:
        name: zoro-backup-creds
        key: storage-account-name
      storageSasToken:
        name: zoro-backup-creds
        key: zoro-blob-sas
  retentionPolicy: "14d"
