apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: nami-objectstore
spec:
  configuration:
    destinationPath: "https://cloudlabbackupsstaging.blob.core.windows.net/nami"
    azureCredentials:
      storageAccount:
        name: nami-backup-creds
        key: storage-account-name
      storageSasToken:
        name: nami-backup-creds
        key: nami-blob-sas
  retentionPolicy: "14d"
