apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nami-cnpg
  namespace: nami
  labels:
    app: cnpg
spec:
  namespaceSelector:
    matchNames:
      - nami
  selector:
    matchLabels:
      cnpg.io/cluster: nami-db
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
