apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nami-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "cf791502-9182-417a-851e-94116fb2565d"
    keyvaultName: "kv-cloudlab-staging"
    tenantId: "7ec184ef-0661-4d19-935b-b0f746d3e8a7"
    objects: |
      array:
        - |
          objectName: nami-db-user
          objectType: secret
        - |
          objectName: nami-db-password
          objectType: secret
        - |
          objectName: storage-account-name
          objectType: secret
        - |
          objectName: nami-blob-sas
          objectType: secret
        - |
          objectName: nami-telegram-bot-token
          objectType: secret
        - |
          objectName: nami-telegram-chat-id
          objectType: secret
  secretObjects:
    - secretName: nami-db-credentials
      type: kubernetes.io/basic-auth
      data:
        - objectName: nami-db-user
          key: username
        - objectName: nami-db-password
          key: password
    - secretName: nami-n8n-env
      type: Opaque
      data:
        - objectName: nami-db-user
          key: DB_POSTGRESDB_USER
        - objectName: nami-db-password
          key: DB_POSTGRESDB_PASSWORD
    - secretName: nami-backup-creds
      type: Opaque
      data:
        - objectName: storage-account-name
          key: storage-account-name
        - objectName: nami-blob-sas
          key: nami-blob-sas
    - secretName: nami-telegram-creds
      type: Opaque
      data:
        - objectName: nami-telegram-bot-token
          key: TELEGRAM_BOT_TOKEN
        - objectName: nami-telegram-chat-id
          key: TELEGRAM_CHAT_ID
