apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zoro-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - zoro.cloudlab.rahatahsan.com
      secretName: zoro-tls
  rules:
    - host: zoro.cloudlab.rahatahsan.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zoro-n8n
                port:
                  number: 3008
