apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: zoro-cnpg
  namespace: zoro
  labels:
    app: cnpg
spec:
  namespaceSelector:
    matchNames:
      - zoro
  selector:
    matchLabels:
      cnpg.io/cluster: zoro-db
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
