apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: luffy-objectstore
spec:
  configuration:
    destinationPath: "https://cloudlabbackupsstaging.blob.core.windows.net/luffy"
    azureCredentials:
      storageAccount:
        name: luffy-backup-creds
        key: storage-account-name
      storageSasToken:
        name: luffy-backup-creds
        key: luffy-blob-sas
  retentionPolicy: "14d"
