apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: luffy-cnpg
  namespace: luffy
  labels:
    app: cnpg
spec:
  namespaceSelector:
    matchNames:
      - luffy
  selector:
    matchLabels:
      cnpg.io/cluster: luffy-db
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
