apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: luffy-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "8f42f940-22dc-4a0e-aec9-3ac5ab24d19a"
    keyvaultName: "kv-cloudlab-staging"
    tenantId: "7ec184ef-0661-4d19-935b-b0f746d3e8a7"
    objects: |
      array:
        - |
          objectName: luffy-db-user
          objectType: secret
        - |
          objectName: luffy-db-password
          objectType: secret
        - |
          objectName: storage-account-name
          objectType: secret
        - |
          objectName: luffy-blob-sas
          objectType: secret
        - |
          objectName: luffy-telegram-bot-token
          objectType: secret
        - |
          objectName: luffy-telegram-chat-id
          objectType: secret
  secretObjects:
    - secretName: luffy-db-credentials
      type: kubernetes.io/basic-auth
      data:
        - objectName: luffy-db-user
          key: username
        - objectName: luffy-db-password
          key: password
    - secretName: luffy-n8n-env
      type: Opaque
      data:
        - objectName: luffy-db-user
          key: DB_POSTGRESDB_USER
        - objectName: luffy-db-password
          key: DB_POSTGRESDB_PASSWORD
    - secretName: luffy-backup-creds
      type: Opaque
      data:
        - objectName: storage-account-name
          key: storage-account-name
        - objectName: luffy-blob-sas
          key: luffy-blob-sas
    - secretName: luffy-telegram-creds
      type: Opaque
      data:
        - objectName: luffy-telegram-bot-token
          key: TELEGRAM_BOT_TOKEN
        - objectName: luffy-telegram-chat-id
          key: TELEGRAM_CHAT_ID
